### ISSUE TITLE
Error while using MLSL with Intel Deep Learning SDK

### ISSUE THREAD

**Issue by giridhar-narasimhamurthy** [intel/MLSL#10]
I see the following error when I am trying to create a model using Intel DL Training tool:

I0925 18:53:53.454358   222 caffe.cpp:329] Starting Optimization
I0925 18:53:53.454391   222 solver.cpp:495] Solving OneMoreTry
I0925 18:53:53.454398   222 solver.cpp:496] Learning Rate Policy: inv
**(222): /localdisk/jenkins/mlsl-build/src/comms_ep.cpp:CommsAlloc:535: ASSERT 'ptr' FAILED: NULL pointer**
Attempting to use an MPI routine after finalizing MPI

There are some posts about this already that suggests to set MLSL_HEAP_SIZE_GB to 64.

I have the following questions related to this:
1. Where must this env variable be set ? Since I am using it via Intel DL training tool browser user interface, I dont have any way to set this.
2. Is that ASSERT due to out-of-memory condition ? What is the memory requirement for running MLSL ?

**Comment by mshiryaev** [comment]
@giridhar-narasimhamurthy The latest version of MLSL doesn't require explicit specification of MLSL_HEAP_SIZE_GB, the size will be adjusted automatically. Most probably your issue is related with /dev/shm size limitation, by default it is half of RAM size, in that case just increase /dev/shm size.
