### ISSUE TITLE
Where is install.sh

### ISSUE THREAD

**Issue by alheinecke** [intel/MLSL#12]
Hi,

I was trying to follow the installation instructions for non-root installation. Where do I find the install.sh script?

Thanks!

**Comment by SmorkalovME** [comment]
Hi Alexander,

You should download the latest *.tgz package from [releases ](https://github.com/intel/MLSL/releases)page (the latest at this moment is [l_mlsl_2017.2.018](https://github.com/intel/MLSL/releases/download/v2017.2-Preview/l_mlsl_2017.2.018.tgz)). Once you un-tar the package you should see install.sh among the files.

Hope this helps.
Thanks,
