### ISSUE TITLE
ep_server build fails

### ISSUE THREAD

**Issue by rscohn2** [intel/MLSL#15]
The build fails on my ubuntu system. Maybe a difference between MPI's?

`gcc -O2 -I/home/rscohn1/projects/MLSL/mpirt/include -I/home/rscohn1/local/projects/MLSL/eplib/../quant -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -fstack-protector -Wall -Werror -Wall -std=gnu99 -I. -DENABLE_FASTPATH -D_GNU_SOURCE -DENABLE_ASYNC_PROGRESS -lm -o ep_server server.c cqueue.o memory.o env.o sig_handler.o quant.o allreduce_pr.o -z noexecstack -z relro -z now  -L/home/rscohn1/projects/MLSL/mpirt/lib -lmpi -ldl -lrt -lpthread
allreduce_pr.o: In function `allreduce_pr_make_progress':
allreduce_pr.c:(.text+0x2da): undefined reference to `log2'
allreduce_pr.c:(.text+0x385): undefined reference to `pow'
allreduce_pr.c:(.text+0x3a7): undefined reference to `pow'
allreduce_pr.c:(.text+0x5bf): undefined reference to `pow'
allreduce_pr.c:(.text+0x5e5): undefined reference to `pow'
collect2: error: ld returned 1 exit status
Makefile:80: recipe for target 'ep_server' failed
make[1]: *** [ep_server] Error 1
make[1]: Leaving directory '/home/rscohn1/local/projects/MLSL/eplib'
Makefile:226: recipe for target 'eplib/ep_server' failed
make: *** [eplib/ep_server] Error 2
rscohn1@vs-sycl-1:MLSL$`

**Comment by fzou1** [comment]
Hello. You need to add "-lm" option to LDFLAGS in line 58 of eplib/Makefile, as below:
  LDFLAGS += -L$(MPIRT_DIR)/lib -lmpi -ldl -lrt -lpthread **-lm**

**Comment by rscohn2** [comment]
I did a PR: #16

**Comment by SmorkalovME** [comment]
Thanks Robert! PR is merged.
