### ISSUE TITLE
MAX_COMPUTE_OP is defined as 400 which is too small and failed to run distributed resnet50 and resnet101

### ISSUE THREAD

**Issue by moting9** [intel/MLSL#2]
MAX_COMPUTE_OP is defined as 400 which is too small and failed to run distributed resnet50 and resnet101

(106827): /localdisk/jenkins/mlsl-build/src/mlsl_impl.h:ComputeOpImpl:568: ASSERT 'op_count < MAX_COMPUTE_OP' FAILED: too many operations (current count 400, limit 400)

**Comment by artemry-nv** [comment]
Will be fixed in Intel MLSL 2017 Preview.
