### ISSUE TITLE
Multi-node Training

### ISSUE THREAD

**Issue by fastalgo** [intel/MLSL#3]
I think Intel Caffe is using MLSL for distributed processing.

Is there any paper or report about how Intel Caffe conducts multi-node processing?

E.g. the way of communication, data partition, communication frequency, strong scaling efficiency.

Is Intel Caffe using the same idea of Parameter Sever (J. Dean, NIPS 2012)?

**Comment by artemry-nv** [comment]
> I think Intel Caffe is using MLSL for distributed processing.
> Is there any paper or report about how Intel Caffe conducts multi-node processing?
> E.g. the way of communication, data partition, communication frequency, strong scaling efficiency.

To the best of our knowledge, Intel Caffe supports only data parallelism and synchronous SGD now - this means that Allreduce for gradients is performed each time before SGD call. Meantime Intel MLSL itself supports model and hybrid parallelism either.

You can find additional information about Intel MLSL in the [Intel® Machine Learning Scaling Library Developer Guide and Reference](https://github.com/01org/MLSL/blob/master/doc/Developer_Guide_and_Reference.pdf).

**Comment by fastalgo** [comment]
@itemko Thanks so much!
