### ISSUE TITLE
Memory corrupted error : running MLSL on multiple node

### ISSUE THREAD

**Issue by tarunjainsagar** [intel/MLSL#5]
@itemko @mshiryaev @argretzi @szollinx @rpulid2 @

tarun@pas-lab-server7:/nfs$ mpirun -f /nfs/host_file -n 2 /nfs/mlsl_test 1
built with MLSL API version: 1.0, used MLSL API version: 1.0
built with MLSL API version: 1.0, used MLSL API version: 1.0
*** Error in `/nfs/common/install/mpich/mpich_3.0.4-install/bin/hydra_pmi_proxy': malloc(): memory corruption (fast): 0x0000000001c7bfa0 ***
[mpiexec@pas-lab-server7] control_cb (./pm/pmiserv/pmiserv_cb.c:202): assert (!closed) failed
[mpiexec@pas-lab-server7] HYDT_dmxu_poll_wait_for_event (./tools/demux/demux_poll.c:77): callback returned error status
[mpiexec@pas-lab-server7] HYD_pmci_wait_for_completion (./pm/pmiserv/pmiserv_pmci.c:197): error waiting for event
[mpiexec@pas-lab-server7] main (./ui/mpich/mpiexec.c:331): process manager error waiting for completion

**Host file contains 2 ip addresses of two servers, where ssh is already configured.**

**Comment by artemry-nv** [comment]
As far as I see you used MPICH - could you please try the similar scenario with Intel MPI Library runtime environment (just to source mlslvars.sh)?

**Comment by tarunjainsagar** [comment]
@argretzi @mshiryaev  @szollinx  @rpulid2 
@itemko thanks for the reply.
does intel MLSL support mpich ??
I want to build intel caffe using MLSL ??
intel mpi is not freely available for commercial use, so i do not prefer to use it as of now.

**Comment by tarunjainsagar** [comment]
@itemko @argretzi @mshiryaev @szollinx @rpulid2 

mpirun -f  -n 2 ./mlsl_test 1

This command passes all the test. Problem comes only when we provide hostfile.
Please suggest some solutions. Also tell that " Is MPICH supported by MLSL" 

because in the intel caffe at this link: https://github.com/intel/caffe/wiki/Multinode-guide
They have used MPICH with MLSL.

**Comment by artemry-nv** [comment]
@tarun1325 Intel MPI Library is free now.
You can download it from the [official site](https://software.intel.com/en-us/intel-mpi-library).
