### ISSUE TITLE
assert (!(pollfds[i].revents & ~POLLIN & ~POLLOUT & ~POLLHUP & ~POLLERR)) failed : running MLSL on multiple node

### ISSUE THREAD

**Issue by tarunjainsagar** [intel/MLSL#6]
@argretzi @mshiryaev @itemko @szollinx @rpulid2 

tarun@pas-lab-server7:/nfs$ mpirun -f /nfs/host_file -n 2 /nfs/mlsl_test 1
built with MLSL API version: 1.0, used MLSL API version: 1.0
built with MLSL API version: 1.0, used MLSL API version: 1.0
[proxy:1:1@pas-lab-server7] HYDT_dmxu_poll_wait_for_event (./tools/demux/demux_poll.c:71): assert (!(pollfds[i].revents & ~POLLIN & ~POLLOUT & ~POLLHUP & ~POLLERR)) failed
[proxy:1:1@pas-lab-server7] main (./pm/pmiserv/pmip.c:206): demux engine error waiting for event
*** Error in `/nfs/common/install/mpich/mpich_3.0.4-install/bin/hydra_pmi_proxy': malloc(): memory corruption (fast): 0x0000000000b73f80 ***
[mpiexec@pas-lab-server7] control_cb (./pm/pmiserv/pmiserv_cb.c:202): assert (!closed) failed
[mpiexec@pas-lab-server7] HYDT_dmxu_poll_wait_for_event (./tools/demux/demux_poll.c:77): callback returned error status
[mpiexec@pas-lab-server7] HYD_pmci_wait_for_completion (./pm/pmiserv/pmiserv_pmci.c:197): error waiting for event
[mpiexec@pas-lab-server7] main (./ui/mpich/mpiexec.c:331): process manager error waiting for completion

**Comment by artemry-nv** [comment]
Hi @tarun1325 

Could you please try to run this scenario with Intel MPI Library?
Intel MPI Library is free now.
You can download it from the [official site](https://software.intel.com/en-us/intel-mpi-library).
