### ISSUE TITLE
Multi-node Training Deadlock

### ISSUE THREAD

**Issue by vamatya** [intel/MLSL#7]
With MLSL 2017 Preview, Intel Caffe on mnist dataset deadlocks for runs on more than 2 nodes. Two node executions are occasionally succesful and gets deadlocked the other times. The caffe outputs where it gets stuck are: 
/ ---------------------------------------------
I0501 12343 net.cpp:424] Network initialization done.                                                  
I0501 12343 solver.cpp:119] Solver scaffolding done.                                                   
I0501 12343 caffe.cpp:318] Configuring multinode setup                                                 
I0501 12343 caffe.cpp:320] Starting Multi-node Optimization in MLSL environment                        
W0501 12343 multi_sync.hpp:124] RUN: PER LAYER TIMINGS ARE ENABLED, SINGLE DB SPLITTING IS DISABLED    
W0501 12343 multi_sync.hpp:116] synchronize_params: bcast 

/ ---------------------------------------------

I0501 26610 layer_factory.hpp:114] Creating layer mnist
I0501 26610 net.cpp:183] Creating Layer mnist
I0501 26610 net.cpp:838] mnist -> data
I0501 26610 net.cpp:838] mnist -> label
W0501 26610 net.cpp:247] SetMinibatchSize 64
I0501 11726 db_lmdb.cpp:72] Opened lmdb /caffe/data/mnist/mnist_train_lmdb                                                   
I0501 22362 db_lmdb.cpp:72] Opened lmdb /caffe/data/mnist/mnist_train_lmdb                                                   
I0501 26702 db_lmdb.cpp:72] Opened lmdb /caffe/data/mnist/mnist_train_lmdb
/ ---------------------------------------------

Run Configurations: 
MLSL: 2017 Preview
IntelCaffe Commit: f96b759f71b2281835f690af267158b82b150b5c
Intel Compiler: 16.0.1 (gcc: 4.9.2)
Intel MPI Version: Intel(R) MPI Library 5.1.2
Platform: x86 (Xeon)
command: mpirun -n X -ppn Y -machinefile hostfile $CAFFEBINDIR/caffe train --solver=lenet_solver.prototxt

Is there a way to control the number of threads MLSL uses? 
Also, may I also ask where can I get the following document? https://github.com/01org/MLSL/blob/master/doc/Developer_Guide_and_Reference.pdf

Thanks!

**Comment by mshiryaev** [comment]
Hello,

Please check that you compiled Caffe with ALLOW_LMDB_NOLOCK=1 if you use the same lmdb database from different MPI ranks.

Since MLSL 2017 Preview there is no Developer_Guide_and_Reference.pdf, only Developer_Guide.pdf
The MLSL API is described in doxygen format, use ./doc/API_Reference.htm as start page.

**Comment by vamatya** [comment]
@mshiryaev  Thank you for your prompt reply! ALLOW_LMDB_NOLOCK := 1 was missing for my build configuration. However, after enabling it and rebuilding caffe, the output for a 4 node run is still stuck at the above ( 2nd) output.

**Comment by mshiryaev** [comment]
/caffe/data/mnist/mnist_train_lmdb - is it shared directory? Do all ranks have access to db?
Try to remove lock.mdb file from this directory that can be left after previous launches.

**Comment by vamatya** [comment]
Yes, its a shared directory. Yes, all ranks have to access the db (although I don't know how to manually pass this info to caffe; like the one needed for mlsl_test binary). With the lock.mdb file removed before each try, the runs still get stuck.

**Comment by mshiryaev** [comment]
How much MPI processes do you create per node? If there are more than 1 process per node then internal MLSL processes will be pinned to the same cores and that can lead to slowdown. By the way for multi-node training over IntelCaffe/MLSL it is enough to use 1 MPI process per node, all single node parallelism will be handled over OpenMP threads. So take that into account when using MLSL: some cores should be allocated for computation only (can be controlled over OMP_NUM_THREADS and KMP_AFFINITY environment variables) and some cores for communication only (over MLSL_SERVER_AFFINITY), and these core subsets should not intersect.

**Comment by vamatya** [comment]
One process per node need to be created for me at the moment. I'm passing -n 4 -ppn 1 argument to mpirun to control this. I tried with OMP_NUM_THREADS=20  or 16; and KMP_AFFINITY=granularity=fine,compact. Each node I'm testing on has two sockets with 10 cores each (hyperthreading disabled).  'top' on each of the nodes show that 4 mlsl processes are active, with only 1 caffe process active in only one of the nodes. Btw, how do I define MLSL_SERVER_AFFINITY?

**Comment by mshiryaev** [comment]
Try these settings:
KMP_AFFINITY="proclist=[0-15],granularity=thread,explicit" KMP_HW_SUBSET=1t MLSL_SERVER_AFFINITY=19,18,17,16 

MLSL_SERVER_AFFINITY is described in MLSL developer guide.

**Comment by vamatya** [comment]
Seems, LMDB does not work well with shared directory. After moving the database to nonshared directory, caffe with MLSL worked on 4 nodes. 
However I have another question for which I'm not sure if I should create another issue. The multinode (4) runs get successful after repeated submission of the same command. Mostly I get 
/-------------
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
/-------------
However for 8 node runs, it doesn't seem to go beyond the above error with multiple try. Any suggestion? 

@mshiryaev Again, thanks a lot for your helpful comments.

**Comment by mshiryaev** [comment]
I see that you use pretty old IMPI: Intel MPI Version: Intel(R) MPI Library 5.1.2

Try to use IMPI runtime from MLSL package.
Source mlslvars.sh and it should overlap IMPI which you sourced before.

**Comment by vamatya** [comment]
I tried that. Now my 'mpirun' points to $MLSL_ROOT/intel64/bin/mpirun. It ran once for 6 node run. But no luck with more than that. 

Thanks!

**Comment by mshiryaev** [comment]
Check on each nodes that there are no stalled files in /dev/shm which can be left after unsuccessful launches.

**Comment by vamatya** [comment]
I see no stalled files in /dev/shm leftover on the nodes.

**Comment by mshiryaev** [comment]
Ok, then check that you are able to run simple IMB-MPI1 benchmark on these nodes.
For example, mpiexec.hydra -n <N> -ppn 1 -hosts <host1, ..., hostN>IMB-MPI1 allreduce
MLSL works over MPI so if MPI works then MLSL should work too.
Also I would suggest to try launch Caffe with MLSL_NUM_SERVERS=0.

**Comment by vamatya** [comment]
https://pastebin.com/LXkqbFYK is the output for the "IMB-MPI1 allreduce" benchmark test on 8 nodes. The run uses the mpiexec.hydra that came with MLSL. I tried to lunch Caffe with MLSL_NUM_SERVERS=0, runs on 4 node without any mlsl processes. However 8 node launch is still not a success.

**Comment by mshiryaev** [comment]
Do you able to run mlsl_test from MLSL package on 8 nodes?
mpiexec.hydra -n 8 -ppn 1 -hosts ... ./mlsl_test 1

**Comment by vamatya** [comment]
Yes. All the tests seem to pass with mlsl_test, on 8 nodes.

**Comment by mshiryaev** [comment]
Then it can be Caffe-specific issue, maybe related with reading from lmdb. You can also try to use dummy data layer to check that assumption.
