### ISSUE TITLE
Can not run mlsl_test

### ISSUE THREAD

**Issue by ganshaoduo** [intel/MLSL#8]
Hi guys,

I installed MLSL in order to train models with multi-nodes.
I started two Docker containers in my local machine to do some test. 
However, when I run mlsl_test as specified in Developer Guide, I got errors like this:

[root@c87b5ae7eb7a test]# mpirun -n 2 -ppn 1 ./mlsl_test 1

built with MLSL API version: 1.0, used MLSL API version: 1.0
built with MLSL API version: 1.0, used MLSL API version: 1.0
=========================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 8316 RUNNING AT c87b5ae7eb7a
=   EXIT CODE: 11
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
==================================================================================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 8316 RUNNING AT c87b5ae7eb7a
=   EXIT CODE: 11
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
=========================================================================
   Intel(R) MPI Library troubleshooting guide:
      https://software.intel.com/node/561764
=========================================================================

If I run [root@c87b5ae7eb7a test]# mpirun -n 2 -ppn 1 -hostfile ~/mpd.hosts ./mlsl_test 1
I got exactly same error.

How do I know where is wrong ? My two containers can connect with each other through ssh.
It almost took me a whole day... Thanks a lot if you can give me some advice!

**Comment by mshiryaev** [comment]
@ganshaoduo Try to set the environment variable MLSL_NUM_SERVERS=0.

**Comment by ganshaoduo** [comment]
Thanks! 

I set MLSL_NUM_SERVERS=0, but I just got same error when I run 'mpirun -n 2 -ppn 1 ./mlsl_test 1'.

If I run 'mpirun -n 2 -ppn 1 -hostfile ~/mpd.hosts ./mlsl_test 1' several times, the EXIT CODE can be either '11' or '1'.

**Comment by mshiryaev** [comment]
Try to launch simple MPI program, for example IMB-MPI1 pingpong if you have Intel MPI installed.
mpirun -n 2 -ppn 1 IMB-MPI1 pingpong
If it works then mlsl_test with MLSL_NUM_SERVERS=0 should work too.

**Comment by zj88** [comment]
Hi @mshiryaev MLSL_NUM_SERVERS=0 helped me with my problem with running mlsl_test, but can you tell what MLSL_NUM_SERVERS=0 means? Don't we lose multinode properties by this? Not much info on endpoint servers in Dev Guide

**Comment by mshiryaev** [comment]
Hi @zj88. MLSL_NUM_SERVERS defines number of separate communication processes driving communication. In case of MLSL_NUM_SERVERS=0 we switch to implementation wo separate processes and communication driving is performed from user process (what is expectedly slower than with MLSL_NUM_SERVERS > 0 on medium/large messages).
Both approaches are applicable for multi-node, the main difference is performance.
