### ISSUE TITLE
Run mlsl_test on multi-node

### ISSUE THREAD

**Issue by Rpona** [intel/MLSL#9]
Hi, I tested the mlsl_test with this command "mpirun -n 4 -ppn 1 /opt/intel/mlsl_2017.1.016/test/mlsl_test 1" and it ran successfully.
But if I tried "mpirun -n 4 -ppn 1 -machinefile ~/mpd.hosts /opt/intel/mlsl_2017.1.016/test/mlsl_test 2 1"
, it just print "built with MLSL API version: 1.0, used MLSL API version: 1.0" and keep the status.
Does this sample code support running on the multi nodes?
Thank you.

**Comment by artemry-nv** [comment]
Hi @Rpona 

Could you please check that MPI itself works fine, e.g. with:
mpirun -n 4 -ppn 1 -machinefile ~/mpd.hosts hostname
and simple "Hello World" MPI test.
BTW which MPI do you use?

Additionally please check and clean up (if there're a lot of stale files) /dev/shm files.

**Comment by Rpona** [comment]
Hi @itemko 
Thanks for your reply.
I used intel mpi and mpi runtime build-in of mlsl package. 
Both they met the same issues.
I used this hello word.c as below and it can run well. 
http://mpitutorial.com/tutorials/mpi-hello-world/
I clean up /dev/shm files., but it didn't work.
(BTW, before I compiling intel caffe with USE_MLSL=1, it can run well. )

**Comment by Rpona** [comment]
Hi @itemko 
I fixed this issue with 
export MLSL_NUM_SERVERS=0
export MLSL_STATS=1
I can run mlsl_test on multi-node now. Thank you!
